### ISSUE TITLE
不要な変数について

### ISSUE THREAD

**Issue by mizushima1226** [macmeals/todo-app#1]
https://github.com/macmeals/todo-app/blob/26d206e02965d505bca840bea72b100e9b0bccaf/src/index.js#L16-L20

listItemをappendChildした時の返却ちをshowItemとして変数に格納していますが、listItemもshowItemも同一のNodeです

https://github.com/macmeals/todo-app/blob/26d206e02965d505bca840bea72b100e9b0bccaf/src/index.js#L28

こちらではshowItemではなく、listItemを参照しているので、listItemに統一してしまうのがシンプルかと思います👍

showcompbtnでも同じことが起きています👀

**Comment by macmeals** [comment]
listItemに統一しました。また不要な格納変数があったのそれを全体的に見直しました。

**Comment by mizushima1226** [comment]
LGTMです〜〜
このissueはcloseしてもらってOKです〜
