### ISSUE TITLE
inputフォーカス時にエンターキーで画面がリロードされる

### ISSUE THREAD

**Issue by mizushima1226** [macmeals/todo-app#2]
タイトルの通りです
動作確認のほどお願いします〜
submitされているため画面リロードされていると思います👀

**Comment by macmeals** [comment]
ご確認ありがとうございます。
`<form onsubmit="return false;">
Formのonsubmit属性をFalseにするコードを追加しました！

**Comment by mizushima1226** [comment]
submitのデフォルトの動作を止める方法があるので、
第４回資料の「JavaScriptとイベント」あたりのやり方が参考になるかと🙏
エンターキーで何も起きない、ではなくエンターキーでもtodoの登録ができるようになります〜

**Comment by macmeals** [comment]
再度修正しました〜
preventDefault();を使ってみました。
